"""add_auth_system_tables

Revision ID: 227b8598a382
Revises: None
Create Date: 2026-05-12 22:22:40.301187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227b8598a382'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=200), nullable=False),
    sa.Column('provider_email', sa.String(length=200), nullable=True),
    sa.Column('provider_data', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_provider_identity')
    )
    op.create_index('idx_auth_identities_provider_email', 'auth_identities', ['provider_email'], unique=False)
    op.create_index(op.f('ix_auth_identities_id'), 'auth_identities', ['id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_ip', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_tokens_user_revoked_expires', 'refresh_tokens', ['user_id', 'revoked', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_player_fixtures_id'), table_name='player_fixtures')
    op.drop_table('player_fixtures')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))

    # Backfill: Create email identities for existing users
    # and mark existing users as email_verified (they already have accounts)
    op.execute("""
        UPDATE users SET email_verified = 1 WHERE email_verified IS NULL
    """)
    op.execute("""
        INSERT INTO auth_identities (user_id, provider, provider_id, provider_email, is_primary, created_at)
        SELECT id, 'email', email, email, 1, created_at
        FROM users
        WHERE NOT EXISTS (
            SELECT 1 FROM auth_identities ai WHERE ai.user_id = users.id
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'email_verified')
    op.create_table('player_fixtures',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gameweek_id', sa.INTEGER(), nullable=True),
    sa.Column('squad_player_id', sa.INTEGER(), nullable=True),
    sa.Column('fixture_id', sa.INTEGER(), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('bonus_points', sa.INTEGER(), nullable=True),
    sa.Column('total_points', sa.INTEGER(), nullable=True),
    sa.Column('minutes', sa.INTEGER(), nullable=True),
    sa.Column('goals_scored', sa.INTEGER(), nullable=True),
    sa.Column('clean_sheet', sa.BOOLEAN(), nullable=True),
    sa.Column('goals_conceded', sa.INTEGER(), nullable=True),
    sa.Column('was_home', sa.BOOLEAN(), nullable=True),
    sa.Column('opponent', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['squad_player_id'], ['squad_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_fixtures_id'), 'player_fixtures', ['id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_revoked_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_auth_identities_id'), table_name='auth_identities')
    op.drop_index('idx_auth_identities_provider_email', table_name='auth_identities')
    op.drop_table('auth_identities')
    # ### end Alembic commands ###
